### ISSUE TITLE
QLatin1String has no member named ‘arg’

### ISSUE THREAD

**Issue by sonichy** [cyberos/libcyber-system#1]
networkmanagement/networkmodelitem.cpp:323:37: error: ‘class QLatin1String’ has no member named ‘arg’
      return QLatin1String("%1 (%2)").arg(m_name).arg(m_deviceName);

Change to QString ?

**Comment by itsvic-dev** [comment]
Again, old Qt version. 
![image](https://user-images.githubusercontent.com/17727163/108625085-2b21c480-7449-11eb-9fe1-307a18eceae0.png)
